In [ ]:
Свойства сложения и умножения матриц

In [ ]:
(k * l)*A = k*(l * A)

In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]], float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
k = 2
l = 3
b = k * l
B = np.dot(a, b)
print(B)

[[ 6. 12. 18.]
 [24. 30. 36.]
 [42. 48. 54.]]


In [5]:
C = np.dot(l, a) * k
print(C)

[[ 6. 12. 18.]
 [24. 30. 36.]
 [42. 48. 54.]]


In [ ]:
C = B

In [ ]:
k * (A + B) = k * A + k * B

In [7]:
import numpy as np
d = np.add(c,b)
print(a)
print('')
b = np.array([[9,8,7], [6,5,4], [3,2,1]], float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [8]:
c = np.add(a,b)*k
print(c)


[[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]


In [10]:
d = np.dot(a,k) + np.dot(b,k)
print(d)

[[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]


In [ ]:
c = d

In [ ]:
(k + l) * A = k * A + l * A

In [12]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], float)
k = 2
l = 3
m = k + l
b = np.dot(m,a)
print(b)

[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]


In [13]:
e = np.dot(k,a)
print(e)
print('')
f = np.dot(l, a)
print(f)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


In [14]:
c = np.add(e,f)
print(c)

[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]


In [ ]:
c = b

In [ ]:
(A * B)*C = A*(B * C)

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], float)
b = np.array([[9,8,7], [6,5,4], [3,2,1]], float)
c = np.array([[1,1,1], [1,1,1], [1,1,1]], float)

In [15]:
d = np.dot(a,b)
print(d)

[[150. 180. 210.]
 [330. 405. 480.]
 [510. 630. 750.]]


In [16]:
e = np.dot(d,c)
print(e)

[[11700. 14400. 17100.]
 [26550. 32625. 38700.]
 [41400. 50850. 60300.]]


In [17]:
f = np.dot(b,c)
print(f)

[[ 750.  900. 1050.]
 [1650. 2025. 2400.]
 [2550. 3150. 3750.]]


In [18]:
g = np.dot(f,a)
print(g)

[[11700. 14400. 17100.]
 [26550. 32625. 38700.]
 [41400. 50850. 60300.]]


In [ ]:
g = e

In [ ]:
A * (B + C) = A * B + A * C

In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]], float)
b = np.array([[9,8,7], [6,5,4], [3,2,1]], float)
c = np.array([[1,1,1], [1,1,1], [1,1,1]], float)

In [3]:
e = np.add(b, c)
print(e)

[[10.  9.  8.]
 [ 7.  6.  5.]
 [ 4.  3.  2.]]


In [4]:
f = np.dot(a, e)
print(f)

[[ 36.  30.  24.]
 [ 99.  84.  69.]
 [162. 138. 114.]]


In [5]:
d = np.dot(a, b)
g = np.dot(a, c)
h = np.add(d,g)
print(h)

[[ 36.  30.  24.]
 [ 99.  84.  69.]
 [162. 138. 114.]]


In [ ]:
h = f

In [ ]:
Задание 5.1

In [1]:
import numpy as np
a = np.array([[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1]], float)
b = np.dot(a, 5)
print(b)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [3]:
c = np.linalg.inv(b)
print(c)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [ ]:
Задание 5.2

In [7]:
import numpy as np
a = np.array([[1,2,3], [4,0,6], [7,8,9]], float)
print(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [8]:
np.linalg.det(a)

59.999999999999986

In [ ]:
Задание 5.3

In [9]:
import numpy as np
a = np.array([[1,2,3], [4,0,6], [7,8,9]], float)
print(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [10]:
k = np.linalg.inv(a)
print(k)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [ ]:
Задание 2 Пример матрицы 4х4 с рангом 1

In [4]:
a = np.array([[0,0,0,1],[0,0,0,2],[0,0,0,3],[0,0,0,4]])
np.linalg.matrix_rank(a, 0.0001)

1

In [ ]:
Задание 5.4

In [19]:
import numpy as np
a = np.array([1,5], float)
b = np.array([2,8], float)
np.dot(a,b)

42.0

In [ ]:
Задание 5.5

In [1]:
import numpy as np
a = np.array([1,5,0], float)
b = np.array([2,8,7], float)
c = np.array([7,1.5,3], float)
v = np.cross(a, b)
print(np.inner(v,c))
w = np.cross(b, c)
print(np.inner(w, a))

228.5
228.5
